services:
  loadbalancer:
    build:
      context: .
    networks:
      - app-network
    ports:
      - "8080:8080"
    labels:
      - "BalanceAlgorithm=roundrobin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ./test
    networks:
      - app-network
    ports:
      - "8081-8089:8081"
    labels:
      - "LoadBalanced=true"
      - "LoadBalancer.min.replicas=1"
      - "LoadBalancer.max.replicas=3"
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  app-network:
    driver: bridge

